expect_error(i18n_switch("lang_ek"), "unsupported language")
expect_true(is.list(i18n_switch("lang_en")))
expect_identical(get_available("soil texture"), c("Clayey", "Loam", "Sandy"))
expect_equal(fertplan:::rem_p_coef_of("Durum wheat", "Seed"), 0.85)
expect_silent(i18n_switch("lang_it"))
expect_identical(get_available("soil texture"), c("Argilloso", "Franco", "Sabbioso"))
expect_equal(fertplan:::rem_p_coef_of("Grano duro", "Seme"), 0.85)
